### ISSUE TITLE
Error while executing the script - expecting token

### ISSUE THREAD

**Issue by SherinMirza** [stoe/action-uses-cli#2]
$ action-uses-cli --enterprise slug
C:\Users\xxx\AppData\Roaming\npm\node_modules\action-uses-cli\node_modules\minimist-options\index.js:101
                                        throw new TypeError(`Expected "${key}" default value to be of type "${expectedType}", got ${prettyPrint(defaultType)}`);
                                        ^

TypeError: Expected "token" default value to be of type "string", got "undefined"
    at C:\Users\xxx\AppData\Roaming\npm\node_modules\action-uses-cli\node_modules\minimist-options\index.js:101:12
    at Array.forEach (<anonymous>)

@stoe where do I set the token to authenticate?

**Comment by stoe** [comment]
@SherinMirza, please provide your token via `--token` (or `-t`) if you do not have a `GITHUB_TOKEN` environment  variable set.

v1.0.2 now also checks for the token and will respond with an error if it is not porovided.

**Comment by SherinMirza** [comment]
@stoe  thanks.
Now getting

_Gathering GitHub action `uses` strings for xxx ... this could take a while
ΓÇ╝  request to https://api.github.com/graphql failed, reason: self signed certificate in certificate chain_

How should i proceed? I tried both with and without connecting to our network but getting same error
